FROM mutator_mutator

################################################################################
# c-ares
# RUN apt-get install -y make autoconf automake libtool
WORKDIR /home/mutator/samples

# clone
# RUN git clone https://github.com/c-ares/c-ares.git
# WORKDIR /home/mutator/samples/c-ares/
# RUN git checkout 809d5e84f3423ab8165650d923acb0e246cbd006
RUN mkdir -p /home/mutator/samples/dev

WORKDIR /home/mutator/samples/dev

# build
COPY samples/dev_harness/ /home/mutator/samples/dev_harness/
RUN ls -la /home/mutator/samples/dev_harness
RUN CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
    SRC="/home/mutator/samples/dev" \
    WORK="/home/mutator/samples/dev/work" \
    OUT="/home/mutator/samples/dev/out" \
    ../dev_harness/build.sh