FROM mutator_deps:2004

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/
RUN mkdir mutator
WORKDIR mutator

COPY modules /home/mutator/modules
COPY build.gradle /home/mutator/
COPY run_mutation.py /home/mutator/
COPY run_seeds.py /home/mutator/
COPY eval_run_seeds.py /home/mutator/
RUN chmod +x run_mutation.py
COPY settings.gradle /home/mutator
RUN echo "llvmBinPath=/bin/" > gradle.properties


RUN gradle clean && gradle build

# set library paths for used shared libraries s.t. the system finds them
ENV LD_LIBRARY_PATH /home/mutator/build/install/LLVM_Mutation_Tool/lib/
# For all subjects provide the path to the default main here. This is based on oss-fuzz convention.
ENV LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc"

# install common dependencies
RUN apt-get update -y && \
    apt-get install -y \
        cmake \
        binutils-dev \
        libcurl4-openssl-dev \
        zlib1g-dev \
        libdw-dev \
        libiberty-dev \
        libssl-dev \
        libelf-dev \
        libdw-dev


# install kcov
WORKDIR /kcov
RUN git clone https://github.com/SimonKagstrom/kcov.git && \
    cd kcov && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j && \
    make install
WORKDIR /
RUN rm -rf /kcov

################################################################################
# common files
COPY samples/common /home/mutator/samples/common

WORKDIR /home/mutator
COPY eval_scripts/* /home/mutator/
