FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && \
    apt-get -y install --no-install-suggests --no-install-recommends \
    automake \
    bison flex \
    build-essential \
    git \
    python3 python3-dev python3-setuptools python-is-python3 \
    libtool libtool-bin \
    libglib2.0-dev \
    wget vim jupp nano bash-completion \
    apt-utils apt-transport-https ca-certificates gnupg dialog \
    libpixman-1-dev

RUN echo deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main >> /etc/apt/sources.list && \
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

RUN echo deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal main >> /etc/apt/sources.list && \
    apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1E9377A2BA9EF27F

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y gcc-10 g++-10 gcc-10-plugin-dev gcc-10-multilib \
    libc++-10-dev gdb lcov

RUN apt-get install -y clang-11 clang-tools-11 libc++1-11 libc++-11-dev \
    libc++abi1-11 libc++abi-11-dev libclang1-11 libclang-11-dev \
    libclang-common-11-dev libclang-cpp11 libclang-cpp11-dev liblld-11 \
    liblld-11-dev liblldb-11 liblldb-11-dev libllvm11 libomp-11-dev \
    libomp5-11 lld-11 lldb-11 llvm-11 llvm-11-dev llvm-11-runtime llvm-11-tools

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 0
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 0

RUN rm -rf /var/cache/apt/archives/*



### Mutator install
RUN ln /bin/clang-11 /bin/clang
RUN ln /bin/clang++-11 /bin/clang++
RUN ln /bin/opt-11 /bin/opt
RUN ln /bin/llvm-config-11 /bin/llvm-config
RUN ln /bin/llvm-ar-11 /bin/llvm-ar
RUN ln /bin/llvm-link-11 /bin/llvm-link

RUN apt-get update
RUN apt install -y \
    curl \
    zip \
    nano \
    htop \
    python3-distutils \
    libzmq3-dev \
    openjdk-11-jdk \
    pkg-config \
    libz-dev \
    libreadline-dev \
    time \
    telnet \
    autoconf \
    libgnutls28-dev

WORKDIR /home/
RUN mkdir -p downloads
WORKDIR /home/downloads
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py

RUN pip3 install wllvm

# ENV PATH "/root/toolchains/build/llvm+clang-901-x86_64-linux-gnu_build/bin/:$PATH"
ENV LLVM_COMPILER "clang"

RUN wget https://downloads.gradle-dn.com/distributions/gradle-6.8-bin.zip
RUN unzip gradle-6.8-bin.zip
RUN mv gradle-6.8 /usr/local/gradle

ENV PATH "/usr/local/gradle/bin/:$PATH"

#### install gllvm
WORKDIR /root/

RUN wget -q -c https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz -O - | tar -xz -C /usr/local

ENV PATH="${PATH}:/root/.cargo/bin:/usr/local/go/bin:/root/go/bin"

RUN go get github.com/SRI-CSL/gllvm/cmd/...