FROM mutator_mutator

################################################################################
# eigen
RUN apt-get install -y make autoconf automake libtool pkg-config \
        libbz2-dev liblzo2-dev liblzma-dev liblz4-dev libz-dev \
        libssl-dev libacl1-dev libattr1-dev lrzip \
	      liblz4-tool lzop zstd lcab genisoimage jlha-utils rar default-jdk
WORKDIR /home/mutator/samples

WORKDIR /home/mutator/samples/libarchive
RUN git clone --depth 1 https://github.com/libarchive/libarchive.git
WORKDIR /home/mutator/samples/libarchive/libarchive
RUN git checkout ede459d2ebb879f5eedb6f7abea203be0b334230

WORKDIR /home/mutator/samples/libarchive
RUN git clone --depth 1 https://gitlab.gnome.org/GNOME/libxml2.git
WORKDIR /home/mutator/samples/libarchive/libxml2
RUN git checkout dea91c97debeac7c1aaf9c19f79029809e23a353

WORKDIR /home/mutator/samples/libarchive
COPY samples/libarchive_harness /home/mutator/samples/libarchive_harness

RUN CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
    SRC="/home/mutator/samples/libarchive" \
    WORK="/home/mutator/samples/libarchive/work" \
    OUT="/home/mutator/samples/libarchive/out" \
    DEPS="/home/mutator/samples/libarchive/deps" \
    /home/mutator/samples/libarchive_harness/build.sh
