FROM mutator_mutator

################################################################################
# arrow
WORKDIR /home/mutator/samples

# clone
RUN apt-get install -y -q --no-install-recommends \
        bison \
        build-essential \
        cmake \
        flex \
        libboost-all-dev \
        ninja-build \
        python3
RUN git clone --depth 1 --recursive https://github.com/apache/arrow.git
WORKDIR /home/mutator/samples/arrow/

# build
COPY samples/arrow_harness /home/mutator/samples/arrow_harness
RUN CC=gclang CXX=gclang++ CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/arrow" \
    WORK="/home/mutator/samples/arrow/work" \
    OUT="/home/mutator/samples/arrow/out" \
    SANITIZER="undefined" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../arrow_harness/build.sh

