FROM mutator_mutator

################################################################################
# guetzli
RUN apt-get install -y libpng-dev
WORKDIR /home/mutator/samples
RUN git clone https://github.com/google/guetzli.git
WORKDIR /home/mutator/samples/guetzli
RUN git checkout 214f2bb42abf5a577c079d00add5d6cc470620d3
COPY samples/guetzli_harness /home/mutator/samples/guetzli_harness

RUN CC=gclang CXX=gclang++ CFLAGS="-g -O2" CXXFLAGS="-g -O2" make -j
RUN gclang++ -g -O2 -static -I. \
        ../guetzli_harness/harness.cc \
        fuzz_target.cc \
        ./bin/Release/libguetzli_static.a \
        -o fuzz_target && \
    get-bc fuzz_target
