FROM mutator_mutator

################################################################################
# woff2
WORKDIR /home/mutator/samples

# clone
RUN apt-get install -y make autoconf automake libtool
RUN git clone https://github.com/google/woff2
WORKDIR /home/mutator/samples/woff2/
RUN git checkout a0d0ed7da27b708c0a4e96ad7a998bddc933c06e
RUN git submodule update --init --recursive

# build
COPY samples/woff2_harness /home/mutator/samples/woff2_harness
RUN CC=gclang CXX=gclang++ CFLAGS="-g" CXXFLAGS="-g" \
    SRC="/home/mutator/samples/woff2" \
    WORK="/home/mutator/samples/woff2/work" \
    OUT="/home/mutator/samples/woff2/out" \
    SANITIZER="undefined" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../woff2_harness/build.sh

