FROM mutator_mutator

################################################################################
# c-ares
RUN apt-get install -y make autoconf automake libtool
WORKDIR /home/mutator/samples

# clone
RUN git clone https://github.com/c-ares/c-ares.git
WORKDIR /home/mutator/samples/c-ares/
RUN git checkout 809d5e84f3423ab8165650d923acb0e246cbd006

# build
COPY samples/c-ares_harness /home/mutator/samples/c-ares_harness
RUN CC=gclang CXX=gclang++ CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/c-ares" \
    WORK="/home/mutator/samples/c-ares/work" \
    OUT="/home/mutator/samples/c-ares/out" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../c-ares_harness/build.sh
