# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

# adapted from: https://github.com/google/fuzzbench/blob/e40c64c9c2f8b78fa521554f6270f16e5587207d/benchmarks/jsoncpp_jsoncpp_fuzzer/Dockerfile

FROM mutator_mutator
RUN apt-get update && apt-get install -y build-essential make curl wget

# # Install latest cmake.
# RUN wget https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.sh && \
#     chmod +x cmake-3.14.5-Linux-x86_64.sh && \
#     ./cmake-3.14.5-Linux-x86_64.sh --skip-license --prefix="/usr/local"

WORKDIR /home/mutator/samples
RUN git clone --depth 1 https://github.com/open-source-parsers/jsoncpp
RUN cd jsoncpp; git checkout 42e892d96e47b1f6e29844cc705e148ec4856448
WORKDIR /home/mutator/samples/jsoncpp

COPY samples/jsoncpp_harness /home/mutator/samples/jsoncpp_harness

RUN CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
    SRC="/home/mutator/samples/jsoncpp" \
    WORK="/home/mutator/samples/jsoncpp/work" \
    OUT="/home/mutator/samples/jsoncpp/out" \
    /home/mutator/samples/jsoncpp_harness/build.sh