FROM mutator_mutator

################################################################################
RUN apt-get install -y make autoconf automake libtool cmake pkg-config
WORKDIR /home/mutator/samples
WORKDIR /home/mutator/samples/libevent
RUN git clone https://github.com/libevent/libevent.git libevent
WORKDIR /home/mutator/samples/libevent/libevent
RUN git checkout 5df3037d10556bfcb675bc73e516978b75fc7bc7 # release-2.1.12-stable

WORKDIR /home/mutator/samples/libevent
COPY samples/libevent_harness /home/mutator/samples/libevent_harness

RUN CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
    SRC="/home/mutator/samples/libevent" \
    WORK="/home/mutator/samples/libevent/work" \
    OUT="/home/mutator/samples/libevent/out" \
    /home/mutator/samples/libevent_harness/build.sh
