FROM mutator_mutator

################################################################################
# harfbuzz
WORKDIR /home/mutator/samples
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y meson pkg-config ragel gtk-doc-tools gcc g++ libfreetype6-dev libglib2.0-dev libcairo2-dev
RUN git clone https://github.com/harfbuzz/harfbuzz.git
WORKDIR /home/mutator/samples/harfbuzz
COPY samples/harfbuzz_harness /home/mutator/samples/harfbuzz_harness
RUN CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/harfbuzz" \
    WORK="/home/mutator/samples/harfbuzz/work" \
    OUT="/home/mutator/samples/harfbuzz/out" \
    ../harfbuzz_harness/build.sh

