FROM mutator_mutator

################################################################################
# curl
WORKDIR /home/mutator/samples

# clone
WORKDIR /home/mutator/samples/curl
RUN git clone --depth 1 https://github.com/curl/curl.git curl
RUN git -C curl checkout -f 7e99db829c5a4aa274a5afad9f7d544a1ab303e4
RUN git clone https://github.com/curl/curl-fuzzer.git curl_fuzzer
RUN git -C curl_fuzzer checkout -f 543b9926cc322a18ad30945dc55d78dbbfa679e1

# build
WORKDIR /home/mutator/samples/curl/curl_fuzzer/
COPY samples/curl_harness /home/mutator/samples/curl_harness
RUN CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/curl" \
    WORK="/home/mutator/samples/curl/work" \
    OUT="/home/mutator/samples/curl/out" \
    SANITIZER="undefined" \
    FUZZ_TARGETS="curl_fuzzer_http" \
    ../../curl_harness/build.sh
