FROM mutator_mutator

################################################################################
# aspell
WORKDIR /home/mutator/samples

# clone
RUN apt-get install -y pkg-config
WORKDIR /home/mutator/samples/aspell/
RUN git clone https://github.com/gnuaspell/aspell.git aspell && \
    cd aspell && \
    git checkout cef82a83afc543caaed0aacc814ea4c15909203f
RUN git clone -b master https://github.com/gnuaspell/aspell-fuzz.git aspell-fuzz && \
    cd aspell-fuzz && \
    git checkout fa4aa32c6bf9573801a7675137e1c31b9f13247f

# build
COPY samples/aspell_harness /home/mutator/samples/aspell_harness
WORKDIR /home/mutator/samples/aspell/aspell-fuzz
RUN CC=gclang CXX=gclang++ CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/aspell" \
    WORK="/home/mutator/samples/aspell/work" \
    OUT="/home/mutator/samples/aspell/out" \
    SANITIZER="undefined" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../../aspell_harness/build.sh

