FROM mutator_mutator

################################################################################
# openthread
WORKDIR /home/mutator/samples

# clone
RUN apt-get install -y autoconf cmake ninja-build
RUN git clone https://github.com/openthread/openthread
WORKDIR /home/mutator/samples/openthread/
RUN git checkout d3464814948a457f33b2df3a02856ab2f3533a19

# build
COPY samples/openthread_harness /home/mutator/samples/openthread_harness
RUN CC=gclang CXX=gclang++ CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/openthread" \
    WORK="/home/mutator/samples/openthread/work" \
    OUT="/home/mutator/samples/openthread/out" \
    SANITIZER="undefined" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../openthread_harness/build.sh

