FROM mutator_mutator

################################################################################
# bloaty
WORKDIR /home/mutator/samples

# clone
RUN apt-get install -y cmake ninja-build g++
RUN git clone --depth 1 https://github.com/google/bloaty.git bloaty

# build
WORKDIR /home/mutator/samples/bloaty/
COPY samples/bloaty_harness /home/mutator/samples/bloaty_harness
RUN CC=gclang CXX=gclang++ CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/bloaty" \
    WORK="/home/mutator/samples/bloaty/work" \
    OUT="/home/mutator/samples/bloaty/out" \
    SANITIZER="undefined" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../bloaty_harness/build.sh

