FROM mutator_mutator

################################################################################
# file
WORKDIR /home/mutator/samples
RUN apt-get install -y  make autoconf automake libtool shtool zlib1g-dev
RUN git clone https://github.com/file/file.git
WORKDIR file
RUN git checkout b2e55e985e75de959b0e2a313e58a5178e7e4182
COPY samples/file_harness /home/mutator/samples/file_harness
RUN ../file_harness/build.sh

