FROM mutator_mutator

################################################################################
# libjpeg-turbo
WORKDIR /home/mutator/samples
RUN apt-get install -y make cmake automake libtool nasm
RUN git clone https://github.com/libjpeg-turbo/libjpeg-turbo.git
WORKDIR libjpeg-turbo
RUN git checkout c23672ce52ae53bd846b555439aa0a070b6d2c07
COPY samples/libjpeg-turbo_harness /home/mutator/samples/libjpeg-turbo_harness
RUN CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/libjpeg-turbo" \
    WORK="/home/mutator/samples/libjpeg-turbo/work" \
    OUT="/home/mutator/samples/libjpeg-turbo/out" \
    ../libjpeg-turbo_harness/build.sh

