FROM mutator_mutator

################################################################################
# vorbis
RUN apt-get install -y automake libtool
WORKDIR /home/mutator/samples

# clone vorbis
RUN git clone https://github.com/xiph/vorbis.git
WORKDIR /home/mutator/samples/vorbis/vorbis
RUN git checkout 83a82dd9296400d811b78c06e9ca429e24dd1e5c

# clone ogg
WORKDIR /home/mutator/samples/vorbis
RUN git clone https://gitlab.xiph.org/xiph/ogg.git
WORKDIR /home/mutator/samples/vorbis/ogg
RUN git checkout e1774cd77f471443541596e09078e78fdc342e4f

# build
WORKDIR /home/mutator/samples/vorbis
COPY samples/vorbis_harness /home/mutator/samples/vorbis_harness
RUN CC=gclang CXX=gclang++ CXXFLAGS="" \
    SRC="/home/mutator/samples/vorbis" \
    WORK="/home/mutator/samples/vorbis/install" \
    OUT="/home/mutator/samples/vorbis/out" \
    LIB_FUZZING_ENGINE="/home/mutator/samples/common/main.cc" \
    ../vorbis_harness/build.sh

