FROM mutator_mutator

################################################################################
# eigen
RUN apt-get install -y cmake mercurial
WORKDIR /home/mutator/samples
RUN git clone https://gitlab.com/libeigen/eigen.git
WORKDIR /home/mutator/samples/eigen
RUN git checkout 11cb7b8372b475d35cf95c6c75de23030301fccd
COPY samples/eigen_harness /home/mutator/samples/eigen_harness

RUN CC=gclang CXX=gclang++ CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
    /home/mutator/samples/eigen_harness/build.sh
