FROM mutator_mutator

################################################################################
# freetype
WORKDIR /home/mutator/samples
RUN apt-get install -y autoconf cmake libtool pkg-config make

# clone
RUN git clone https://github.com/freetype/freetype2-testing.git freetype
WORKDIR /home/mutator/samples/freetype/
RUN git checkout ca6201f250316e6efd445a7fd92c4d82950e4cb0

# build
COPY samples/freetype_harness /home/mutator/samples/freetype_harness
RUN CFLAGS="" CXXFLAGS="" \
    SRC="/home/mutator/samples/freetype" \
    WORK="/home/mutator/samples/freetype/work" \
    OUT="/home/mutator/samples/freetype/out" \
    ../freetype_harness/build.sh

