FROM mutator_mutator

################################################################################
# sqlite3
WORKDIR /home/mutator/samples
RUN apt-get install -y make autoconf automake libtool curl tcl zlib1g-dev
WORKDIR sqlite3
RUN curl -s 'https://sqlite.org/src/tarball/sqlite.tar.gz?r=c78cbf2e86850cc6' -o sqlite3.tar.gz && \
    tar xzf sqlite3.tar.gz --strip-components 1
COPY samples/sqlite3_harness /home/mutator/samples/sqlite3_harness
RUN ../sqlite3_harness/build.sh


