//
// Created by Björn Mathis on 11.09.20.
//

#ifndef LLVM_MUTATION_TOOL_MUTATIONS_H
#define LLVM_MUTATION_TOOL_MUTATIONS_H

#define MALLOC 0
#define FGETS_MATCH_BUFFER_SIZE 1


#endif //LLVM_MUTATION_TOOL_MUTATIONS_H
