//
// Created by Björn Mathis on 11.09.20.
//

#ifndef LLVM_MUTATION_TOOL_MUTATIONS_H
#define LLVM_MUTATION_TOOL_MUTATIONS_H

#define MALLOC 0
#define FGETS_MATCH_BUFFER_SIZE 1
#define SIGNED_LESS_THAN 2
#define SIGNED_GREATER_THAN 3
#define SIGNED_LESS_THAN_EQUALTO 4
#define SIGNED_GREATER_THAN_EQUALTO 5
#define FREE_FUNCTION_ARGUMENT 6
#define PTHREAD_MUTEX 7

#endif //LLVM_MUTATION_TOOL_MUTATIONS_H
